# Generated by Django 2.1.5 on 2019-05-23 11:07

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_postcoment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='', upload_to=post.models.get_post_image_path),
        ),
    ]
